spring.application.name=asha-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aasha-db.cdqqyouowfxn.ap-south-1.rds.amazonaws.com:5432/aasha_db?ssl=true&sslmode=verify-full&sslrootcert=${user.dir}/src/main/resources/certs/global-bundle.pem}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
spring.sql.init.continue-on-error=${SPRING_SQL_INIT_CONTINUE_ON_ERROR:true}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

server.port=8080
